[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not,
# prints a warning asking for you to install it. The watchdog module is not required,
# it's just an optimization. If you know you don't want to install watchdog, you can
# set this to True to disable the warning.
disableWatchdogWarning = false

# By default, Streamlit displays a warning when a user sets both a widget default value in
# the function defining the widget and a widget value via the widget's key in
# `st.session_state`.
showWarningOnDirectExecution = true

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not draw to a Streamlit app.
displayEnabled = true

# Controls whether uncaught app exceptions are displayed in the browser. By default, this
# is set to True and Streamlit displays app exceptions and associated tracebacks in the
# browser.
showErrorDetails = true

[browser]

# Internet address where users should point their browsers in order to connect to the app.
# Can be IP address or DNS name and path.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Port where users can connect to the app.
serverPort = 8501

[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save"
# and @st.cache.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this
# should be set to the same value across all replicas to ensure they all share the same
# signed cookie-generating secret.
cookieSecret = "hiv-survey-analysis-key"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The address where the server will listen for client and browser connections. Use this
# if you want to bind the server to a specific address. If set, the server will only be
# accessible from this address, and not from any other address.
address = "localhost"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Resource Sharing (CORS) for all origins. This is useful
# when you want to make HTTP requests to the app from a web page served by another domain.
enableCORS = false

# Enables support for Cross-Origin Resource Sharing (CORS) for the provided domains.
# Whitelist of domains, such as "domain.com", which are allowed to message the app.
# "\*" means all domains are allowed.
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#1f77b4"

# Background color for the main content area.
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"
